# Generated by Django 4.1.6 on 2023-03-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('num', models.IntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cooking.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шаги',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='ImageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_full_url', models.CharField(default='url', max_length=255, verbose_name='Url Полного изображения')),
                ('img_middle_url', models.CharField(default='url', max_length=255, verbose_name='Url среднего изображения ')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cooking.step', verbose_name='Шаг')),
            ],
        ),
    ]
