# Generated by Django 4.1.6 on 2023-03-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['num'], 'verbose_name': 'Ингредиент для рецепта', 'verbose_name_plural': 'Ингредиенты для рецептов'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='num',
            field=models.IntegerField(default=1, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(blank=True, max_length=200, verbose_name='Количество'),
        ),
    ]
