# Generated by Django 4.1.6 on 2023-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_alter_ingredient_options_ingredient_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeForModerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Рецепт для модерации',
                'verbose_name_plural': 'Рецепт для модерации',
                'db_table': 'recipes_for_moderate',
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['num', 'pk'], 'verbose_name': 'Ингредиент для рецепта', 'verbose_name_plural': 'Ингредиенты для рецептов'},
        ),
    ]
